### ISSUE TITLE
Mumble tab not opening

### ISSUE THREAD

**Issue by Robert-lisper** [rossprogram/circle-z#1]
Mumble tab does not open when clicked - all other tabs open fine. I'm using the .appimage version of circleZ. I'm using Pop_OS! 19.10, a modified version of Ubuntu.

**Comment by kisonecat** [comment]
You probably have to launch Mumble once by hand, in order that the protocol
mumble: gets associated with the application.

**Comment by Robert-lisper** [comment]
I have tried clicking mumble through circlez even with mumble open in the background - nothing happens.

**Comment by kisonecat** [comment]
Does opening a mumble: link in, say, a web browser work?

What DE are you using?  Gnome?

**Comment by Robert-lisper** [comment]
No it does not - after getting a pop-up in my browser asking to open the link with mumble, nothing happens. This issue persisted through multiple restarts and reinstalling Mumble. Perhaps this is a bug on Mumble's end? I am using the default version of gnome 3 provided by Pop_OS!.

**Comment by kisonecat** [comment]
How did you install Mumble?  Did you run apt-get install mumble ?

>

**Comment by Robert-lisper** [comment]
I have tried installing via both apt and snap.

**Comment by kisonecat** [comment]
https://github.com/rossprogram/circle-z/commit/3cb60323611a68872669eb7aae04a9bd55bdbc0a fixes this by presenting your Mumble credentials in the Settings page.  It'll take about 30 minutes for the build to finish, at which point you can download the new version from https://github.com/rossprogram/circle-z/releases/latest
