### ISSUE TITLE
Excessive system message spam

### ISSUE THREAD

**Issue by Robert-lisper** [rossprogram/circle-z#2]
It seems the system is overzealous with the "[user] left/joined the chat" messages - every time one switches between rooms, a new batch of those messages appear, which bury any conversation that you may be having. I know of at least 1 other user who is having the same issue. Below is a screenshot for clarification.
![Screenshot from 2020-06-29 22-49-03](https://user-images.githubusercontent.com/55164889/86088805-e94da380-ba9e-11ea-9fef-ff71ba4dfb36.png)

**Comment by ghost** [comment]
This issue is fixed in [1.8.0](https://github.com/rossprogram/circle-z/releases/tag/v1.8.0) and can be closed.
