### ISSUE TITLE
Error: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by saumyasinghal747** [rossprogram/circle-z#7]
## Description
My friend and I who both live in PST and have Apple computers were trying to log in to Circle Z today and were getting this message when trying to log in: 
```Error: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017```

We're both worried since we have class tomorrow - is there a fix we can do? Thank you so much!!

## Things I've Tried

* Restarting the app
* Opening Devtools: (removed my email/password before taking photo)
<img width="799" alt="image" src="https://user-images.githubusercontent.com/65318685/89251000-d57bec80-d5ca-11ea-9b0d-4808869a0665.png">

* Trying again, toggling WiFi
* ssh into 
```sh
        $ ssh username:password@circlez.rossprogram.org -p 7817
    kex_exchange_identification: Connection closed by remote host
```

**Comment by kisonecat** [comment]
I am so sorry. This is my fault.

I have restarted the server now, so things should be working again for you. Please let me know.
